### ISSUE TITLE
make font size configurable

### ISSUE THREAD

**Issue by jorgheymans** [source-foundry/java-glyph-tester#3]

**Comment by jorgheymans** [comment]
handled in #5

**Comment by chrissimpkins** [comment]
:+1:  starting to come together!  let us know when we can dig in and play with it

**Comment by jorgheymans** [comment]
It's useable already, just not nicely packaged at the moment. There is a
bit of a github learning curve for me as well, but I'm getting there. One
thing I would like to do still also is have the Travis build download
automatically the latest released version and the trunk version so that we
can easily compare what changed for glyphs that have been worked on. Github
has this awesome image compare feature built in, so if we can generate
canvas screenshots automatically and add them to the repository that would
be awesome.

Op di 3 mei 2016 22:23 schreef Chris Simpkins notifications@github.com:

**Comment by chrissimpkins** [comment]
Can you explain the image compare feature in a bit more detail?  We have been talking about a visual glyph diff tool across the entire set for some time.  Is there a way to do this?

**Comment by jorgheymans** [comment]
it's demonstrated here https://github.com/cameronmcefee/Image-Diff-View-Modes . The swipe mode should be very useful for comparing even the smallest of font changes.

**Comment by chrissimpkins** [comment]
Is this on by default for all images in a repository?  I use images all the time in repos and never noticed this.  The two up and onion skin are fantastic and would be incredibly useful for glyph examination.  I wonder if we can develop a way to create images of every individual glyph in any font that could then be committed to a repository as part of any new font build.  Changes in the image as the underlying source changes will then manifest as a commit in the git log and those could be visually diff'd with this GitHub feature.  This would be incredibly useful for libre type projects that involve collaborative work.  We've struggled with this issue in our own project because, though the UFO source files are text and can be diff'd, those diffs do not create readily interpretable information about the visual change that occurred in the glyphs or associated metrics.  Furthermore, UFO source can involve thousands of files and even modest changes might alter hundreds or thousands of lines of UFO source which makes it nearly impossible to review raw source for commits to a libre typeface project in the current era of type source code.

**Comment by chrissimpkins** [comment]
And to expand on the above issue and approach a different problem, it would be interesting to create a tool that generates images for each commonly used glyph renderer (as you are doing here for Java) and diff across these renderers.  A different set of data, but also of tremendous interest.

**Comment by jorgheymans** [comment]
you're pretty much reading my thoughts here :-) Difficult part will be to
extract the renderers, on java it was easy but for example which renderer
do vim or atom use ??

am at work atm, we can have a more detailed discussion when i get back home.

**Comment by chrissimpkins** [comment]
That sounds great Jorg.  No rush. I'm sure that we can track this information down. Look forward to discussing in more detail!

**Comment by chrissimpkins** [comment]
Let me know if it would be easier to discuss these issues outside of this specific project in more detail via our Slack account. Happy to forward an invite

**Comment by jorgheymans** [comment]
sure send on the invite !

**Comment by chrissimpkins** [comment]
mind emailing me your email address (chris@sourcefoundry.org)? I can't find it
